sources:
  soul_over_ai:
    source: https://raw.githubusercontent.com/xoundbyte/soul-over-ai/refs/heads/main/dist/artists.json
external:
  youtube:
    api_key: null # Specify in `config_override.yaml` for local development
sqlite:
  file_location: /app/data/soul_over_ai.sqlite
redis:
  host: redis
