[loggers]
keys=root,uvicorn,uvicorn.error,uvicorn.access

[handlers]
keys=intercept

[formatters]
keys=empty

# --- Loggers ---

[logger_root]
level=INFO
handlers=intercept

[logger_uvicorn]
level=INFO
handlers=intercept
qualname=uvicorn
propagate=0

[logger_uvicorn.error]
level=INFO
handlers=intercept
qualname=uvicorn.error
propagate=0

[logger_uvicorn.access]
level=INFO
handlers=intercept
qualname=uvicorn.access
propagate=0

# --- Handlers ---

[handler_intercept]
# This references the class in logging_intercept.py
class=ai_artist_detector.InterceptHandler
args=()
formatter=empty

# --- Formatters ---

[formatter_empty]
# Loguru handles the formatting, so we leave this empty
format=%(message)s
